= UTA+
:sectanchors:
:toc:

This is an old implementation of the http://doi.org/10.1016/0377-2217(82)90155-2[UTA] method, implemented for 16-bit Windows. It does _not_ run under recent (64-bit) versions of Windows.

Here is the original description, as found in the `MANUAL.DOC` file.

== Original description
The UTA method was originally proposed by E. Jacquet-Lagrèze and J. Siskos in 1982. It has gained popularity thanks to implementation called PREFCALC, written by E. Jacquet-Lagrèze. Then, it was improved and modified by several authors (see the References at the end of the Manual).

UTA+ was written in Borland C++ 3.1 with Object Windows Library, at the Poznan University of Technology, Poland.

The UTA+ software is the latest implementation of the UTA method in Windows environment. It summarizes all important contributions made by other authors and offers some new possibilities, in particular, a “compensation” of marginal utility functions controlled by the user and the use of preference intensities in addition to the ranking defined by the user (see sections 11, 18 and 19).

== Running UTA+

=== Windows XP
UTA+ runs under Windows XP: just make sure there’s no special caracters in the path name (it starts successfully when located in `C:\UTA`, but refuses to start in `C:\UTA+`). I suppose it would also run on other 32-bit versions of Windows.

=== Recent Windows
“16-bit Windows (Win16) and DOS applications will not run on x86-64 versions of Windows due to removal of the virtual DOS machine subsystem” — https://en.wikipedia.org/wiki/X86-64#Windows[Wikipedia]. All versions of Windows since XP come in both 32 and 64-bit versions, https://support.microsoft.com/en-us/kb/827218[check] which one you have (if you bought your computer recently, you most probably have a 64-bit version).

=== Linux
I didn’t manage to make UTA+ run under http://winehq.org/[Wine]. Please contact me if you manage to use UTA+ under Linux.

== List of files

I have received the package as presented here (downloaded from Brice Mayag’s page), except I have extracted the zip files into folders named according to the names of the zip files, and added this `README.adoc` file and `list-files.txt`.

* I believe the files in `Demo` are mostly corrupted or redundant with the ones in `Version complete`.
** The following files in `Demo` contain only FF bytes: `UTAHELP.GID`, `METRO.UTA`, `test.uta`.
** From `Demo/UTAPDEMO.ZIP`, using “Archive Manager” under Linux, I can’t extract `UTAPDEMO.EXE`.
** Those files in `Demo` are identical to their counterpart in `Version complete`, and have the same last-modification date: `Bwcc.dll`, `UTAHELP.HLP`.
** The file `Demo/METRO.UTA` has the exact same size and last-modification date than its counterpart in `Version complete`.
** The file `Demo/UTAHELP.GID` has the same size but another last-modification date than its counterpart in `Version complete`.
** The only remaining file (apart from `WS_FTP.LOG`), which seems possibly valid and is not a duplicate, is `Demo/UTAPDEMO.EXE`.
* I believe all the files in `doc` are corrupted, except for `doc/MANUAL.ZIP`, which contains valid versions of the same files.
** The following files in `doc` only contain a few blocks of FF and 00 bytes: `APPENDIX.DOC`, `CONTENTS.DOC`, `GRAPHE.PPT`, `TITLE.DOC`, `WS_FTP.LOG`.
** The two other files in `doc` will not display properly using LibreOffice: `MANUAL.DOC`, `SCREENS.DOC`.
** The `doc/MANUAL.ZIP` file seem to contain the non-corrupted equivalent files (same sizes, same last-modification dates except for a systematic difference of one hour, but readable content, except for `GRAPHE.PPT` which I can’t open with LibreOffice but which has non trivial content, and except for `WS_FTP.LOG` which is not in the archive).
* `Demo/UTAPDEMO.ZIP` contains three extractable files: `BWCC.DLL`, `CARSDEMO.UTA`, `UTAHELP.HLP`. `UTAHELP.HLP` is identical to the one in `Version complete` (although the one in Demo dates from 1997 versus 1999).
* All files in `Version complete` have non-trivial byte content, except for `WS_FTP.LOG`.
* The archive `Version complete/UTA.zip` is composed, at its root, of the content of `doc/MANUAL.ZIP` plus the content of `Version complete` (identical files and last-modification dates), except for the following differences.
** `BWCC.DLL` is identical to `BWCC.DLL` in `Demo/fUTAPDEMO.ZIP`, not identical to `Version complete/Bwcc.dll`.
** `thierry.r01` is different: 61 bytes, date 2004 versus 65 bytes, date 2006 in `Version complete`.
** `UTAPLUS.EXE` has same size and last-modification date (up to one hour), but the version in the archive differs from the one in the folder.
** There is a systematic one-hour difference in last-modification date.
** `WS_FTP.LOG` is not corrupted in the archive.
* The archive `Version complete/UTA.zip` contains, in the subfolder `Documents and Settings/vincent/Mes documents/logiciels mcda/envoi programme/UTA+/Version complete`, a subset of the files in the root of the same archive (identical contents and last-modification dates), except for `UTAHELP.GID` which is different (though same size).

