= UTA+
:sectanchors:
:toc:

This is an old implementation of the http://doi.org/10.1016/0377-2217(82)90155-2[UTA] method, implemented for 16-bit Windows. It does _not_ run under recent (64-bit) versions of Windows.

Here is the original description, as found in the `MANUAL.DOC` file.

== Original description
The UTA method was originally proposed by E. Jacquet-Lagrèze and J. Siskos in 1982. It has gained popularity thanks to implementation called PREFCALC, written by E. Jacquet-Lagrèze. Then, it was improved and modified by several authors (see the References at the end of the Manual).

UTA+ was written in Borland C++ 3.1 with Object Windows Library, at the Poznan University of Technology, Poland.

The UTA+ software is the latest implementation of the UTA method in Windows environment. It summarizes all important contributions made by other authors and offers some new possibilities, in particular, a “compensation” of marginal utility functions controlled by the user and the use of preference intensities in addition to the ranking defined by the user (see sections 11, 18 and 19).

== Running UTA+

=== Windows XP
UTA+ runs under Windows XP: just make sure there’s no special caracters in the path name (it starts successfully when located in `C:\UTA`, but refuses to start in `C:\UTA+`). I suppose it would also run on other 32-bit versions of Windows.

=== Recent Windows
“16-bit Windows (Win16) and DOS applications will not run on x86-64 versions of Windows due to removal of the virtual DOS machine subsystem” — https://en.wikipedia.org/wiki/X86-64#Windows[Wikipedia]. All versions of Windows since XP come in both 32 and 64-bit versions, https://support.microsoft.com/en-us/kb/827218[check] which one you have (if you bought your computer recently, you most probably have a 64-bit version).

=== Linux
I didn’t manage to make UTA+ run under http://winehq.org/[Wine]. Please contact me if you manage to use UTA+ under Linux.

== Alternatives

The `BWCC.DLL` file in the root comes from the `Version complete/UTA.zip` (where it existed twice, in two different folders) and `Demo/UTAPDEMO.ZIP` archives (all three identical files), whereas the `Alternatives/Bwcc-from-Version-complete-and-Demo.dll` file comes from the `Version complete` and `Demo` folders (identical files). The first one is newer (1999) than the alternative one (1995).

The `UTAPLUS.EXE` file in the root comes from the `Version complete/UTA.zip` (where it existed twice, in two different folders), whereas the `Alternatives/UTAPLUS-from-Version-complete.EXE` comes from the `Version complete` folder. They have the same size and last-modification date (up to one hour) but are not identical.

